[01-May-24 15:24:25 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 15:24:25 - INFO] - bot - Bot stopped.
[02-May-24 11:58:24 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 11:58:24 - INFO] - bot - Lets roll
[02-May-24 12:05:18 - ERROR] - asyncio - Task exception was never retrieved
future: <Task finished name='Task-424' coro=<Session.restart() done, defined at C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py:182> exception=AuthKeyDuplicated('Telegram says: [406 AUTH_KEY_DUPLICATED] - The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")')>
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 184, in restart
    await self.start()
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 144, in start
    raise e
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 120, in start
    await self.send(
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: Telegram says: [406 AUTH_KEY_DUPLICATED] - The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")
[02-May-24 12:07:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 12:07:02 - INFO] - bot - Bot stopped.
[02-May-24 12:17:55 - WARNING] - bot - Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")
[02-May-24 12:17:55 - WARNING] - bot - Bot can't Export Invite link from Force Sub Channel!
[02-May-24 12:17:55 - WARNING] - bot - Please Double check the FORCE_SUB_CHANNEL value and Make sure Bot is Admin in channel with Invite Users via Link Permission, Current Force Sub Channel Value: -1002116699403
[02-May-24 12:17:55 - INFO] - bot - 
Bot Stopped. Join https://t.me/CodeXBotzSupport for support
[02-May-24 12:23:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 12:23:19 - INFO] - bot - Lets roll
[02-May-24 12:32:28 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 12:32:28 - INFO] - bot - Bot stopped.
[02-May-24 12:32:36 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 12:32:36 - INFO] - bot - Lets roll
[02-May-24 12:34:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 12:34:08 - INFO] - bot - Bot stopped.
[02-May-24 12:34:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 12:34:16 - INFO] - bot - Lets roll
[02-May-24 12:34:18 - ERROR] - pyrogram.dispatcher - object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
TypeError: object NoneType can't be used in 'await' expression
[02-May-24 12:34:23 - ERROR] - pyrogram.dispatcher - object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
TypeError: object NoneType can't be used in 'await' expression
[02-May-24 12:35:59 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 12:35:59 - INFO] - bot - Bot stopped.
[02-May-24 12:36:14 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 12:36:14 - INFO] - bot - Lets roll
[02-May-24 12:43:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 12:58:50 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 12:58:50 - INFO] - bot - Bot stopped.
[02-May-24 12:59:15 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 12:59:15 - INFO] - bot - Lets roll
[02-May-24 13:00:26 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 13:00:26 - INFO] - bot - Bot stopped.
[02-May-24 13:00:36 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 13:00:36 - INFO] - bot - Lets roll
[02-May-24 13:06:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 13:06:00 - INFO] - bot - Bot stopped.
[02-May-24 13:06:09 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 13:06:09 - INFO] - bot - Lets roll
[02-May-24 13:09:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 13:09:49 - INFO] - bot - Bot stopped.
[02-May-24 14:18:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:18:13 - INFO] - bot - Lets roll
[02-May-24 14:18:21 - ERROR] - pyrogram.dispatcher - DownloadManager._parse_link() missing 1 required positional argument: 'link'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 14, in download_link
    link = download_manager._parse_link()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DownloadManager._parse_link() missing 1 required positional argument: 'link'
[02-May-24 14:19:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:19:39 - INFO] - bot - Bot stopped.
[02-May-24 14:19:47 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:19:47 - INFO] - bot - Lets roll
[02-May-24 14:25:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 14:25:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:25:17 - INFO] - bot - Bot stopped.
[02-May-24 14:25:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:25:33 - INFO] - bot - Lets roll
[02-May-24 14:28:08 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 14:28:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 14:28:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 14:28:31 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:07 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 14:29:08 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:09 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:10 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:10 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:11 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:12 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:13 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:16 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:19 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:22 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:25 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:25 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:28 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:31 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:35 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:38 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:41 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:44 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:46 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:47 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:47 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:48 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:49 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:50 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:50 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:51 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:53 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:53 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:54 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:55 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:56 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:56 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:57 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:58 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:29:59 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 14:29:59 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:30:00 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 14:37:37 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:37:37 - INFO] - bot - Bot stopped.
[02-May-24 14:37:46 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:37:46 - INFO] - bot - Lets roll
[02-May-24 14:41:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 14:47:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:47:08 - INFO] - bot - Bot stopped.
[02-May-24 14:47:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:47:16 - INFO] - bot - Lets roll
[02-May-24 14:47:23 - ERROR] - pyrogram.dispatcher - DownloadManager.is_url() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 17, in download_link
    print(f"Link {link} is_url: {download_manager.is_url(expect_link)}")
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DownloadManager.is_url() takes from 0 to 1 positional arguments but 2 were given
[02-May-24 14:52:26 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:52:26 - INFO] - bot - Bot stopped.
[02-May-24 14:52:35 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:52:35 - INFO] - bot - Lets roll
[02-May-24 14:53:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:53:00 - INFO] - bot - Bot stopped.
[02-May-24 14:53:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:53:08 - INFO] - bot - Lets roll
[02-May-24 14:56:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:56:10 - INFO] - bot - Bot stopped.
[02-May-24 14:56:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:56:18 - INFO] - bot - Lets roll
[02-May-24 14:57:35 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 14:57:35 - INFO] - bot - Bot stopped.
[02-May-24 14:57:42 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 14:57:42 - INFO] - bot - Lets roll
[02-May-24 15:04:51 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:04:51 - INFO] - bot - Bot stopped.
[02-May-24 15:05:00 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:05:00 - INFO] - bot - Lets roll
[02-May-24 15:18:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:18:36 - INFO] - bot - Bot stopped.
[02-May-24 15:18:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:18:45 - INFO] - bot - Lets roll
[02-May-24 15:19:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:19:11 - INFO] - bot - Bot stopped.
[02-May-24 15:19:21 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:19:21 - INFO] - bot - Lets roll
[02-May-24 15:19:24 - ERROR] - pyrogram.dispatcher - 'dict' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 23, in download_link
    downloaded = await dm.download_file(link, message.chat.id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\download\manager.py", line 12, in download_file
    file_info = self._parse_link(link)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\download\manager.py", line 24, in _parse_link
    parsed_url = urlparse(link)
                 ^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'dict' object has no attribute 'decode'
[02-May-24 15:23:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:23:39 - INFO] - bot - Bot stopped.
[02-May-24 15:23:55 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:23:55 - INFO] - bot - Lets roll
[02-May-24 15:24:44 - ERROR] - pyrogram.dispatcher - 'dict' object has no attribute 'decode'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 23, in download_link
    downloaded = await dm.download_file(link, message.chat.id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\download\manager.py", line 14, in download_file
    file_info = self._parse_link(link)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\download\manager.py", line 26, in _parse_link
    parsed_url = urlparse(link)
                 ^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\anaconda3\Lib\urllib\parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'dict' object has no attribute 'decode'
[02-May-24 15:25:54 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:25:54 - INFO] - bot - Bot stopped.
[02-May-24 15:26:03 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:26:03 - INFO] - bot - Lets roll
[02-May-24 15:26:42 - ERROR] - pyrogram.dispatcher - 'DownloadManager' object has no attribute 'app'
Traceback (most recent call last):
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\download\manager.py", line 58, in download_and_send_media
    file_name = os.path.join(temp_dir, os.path.basename(media_url))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 244, in basename
  File "<frozen ntpath>", line 213, in split
TypeError: expected str, bytes or os.PathLike object, not dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 23, in download_link
    downloaded = await dm.download_and_send_media( message.chat.id,  link,)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\download\manager.py", line 74, in download_and_send_media
    await self.app.send_message(chat_id, "Error downloading and sending media.")
          ^^^^^^^^
AttributeError: 'DownloadManager' object has no attribute 'app'
[02-May-24 15:46:59 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:46:59 - INFO] - bot - Bot stopped.
[02-May-24 15:47:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:47:08 - INFO] - bot - Lets roll
[02-May-24 15:48:25 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:48:25 - INFO] - bot - Bot stopped.
[02-May-24 15:48:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:48:33 - INFO] - bot - Lets roll
[02-May-24 15:49:29 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:49:29 - INFO] - bot - Bot stopped.
[02-May-24 15:49:38 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:49:38 - INFO] - bot - Lets roll
[02-May-24 15:51:20 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:51:20 - INFO] - bot - Bot stopped.
[02-May-24 15:51:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:51:28 - INFO] - bot - Lets roll
[02-May-24 15:52:45 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:52:45 - INFO] - bot - Bot stopped.
[02-May-24 15:53:02 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:53:02 - INFO] - bot - Lets roll
[02-May-24 15:53:53 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:53:53 - INFO] - bot - Bot stopped.
[02-May-24 15:54:03 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:54:03 - INFO] - bot - Lets roll
[02-May-24 15:55:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 15:55:17 - INFO] - bot - Bot stopped.
[02-May-24 15:55:32 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 15:55:32 - INFO] - bot - Lets roll
[02-May-24 16:01:56 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:01:56 - INFO] - bot - Bot stopped.
[02-May-24 16:02:09 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:02:09 - INFO] - bot - Lets roll
[02-May-24 16:03:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:03:17 - INFO] - bot - Bot stopped.
[02-May-24 16:03:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:03:28 - INFO] - bot - Lets roll
[02-May-24 16:07:33 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:07:33 - INFO] - bot - Bot stopped.
[02-May-24 16:08:24 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:08:24 - INFO] - bot - Lets roll
[02-May-24 16:08:28 - ERROR] - pyrogram.dispatcher - 'dict' object has no attribute 'type'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 33, in download_link
    if link.type is "telegram":
       ^^^^^^^^^
AttributeError: 'dict' object has no attribute 'type'
[02-May-24 16:09:30 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:09:30 - INFO] - bot - Bot stopped.
[02-May-24 16:09:40 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:09:40 - INFO] - bot - Lets roll
[02-May-24 16:14:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:14:00 - INFO] - bot - Bot stopped.
[02-May-24 16:14:10 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:14:10 - INFO] - bot - Lets roll
[02-May-24 16:22:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 16:23:59 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:23:59 - INFO] - bot - Bot stopped.
[02-May-24 16:26:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:26:33 - INFO] - bot - Lets roll
[02-May-24 16:27:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:27:13 - INFO] - bot - Bot stopped.
[02-May-24 16:27:21 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:27:21 - INFO] - bot - Lets roll
[02-May-24 16:28:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:28:10 - INFO] - bot - Bot stopped.
[02-May-24 16:28:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:28:19 - INFO] - bot - Lets roll
[02-May-24 16:29:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:29:14 - INFO] - bot - Bot stopped.
[02-May-24 16:29:23 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:29:23 - INFO] - bot - Lets roll
[02-May-24 16:29:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:29:49 - INFO] - bot - Bot stopped.
[02-May-24 16:29:57 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:29:57 - INFO] - bot - Lets roll
[02-May-24 16:31:47 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:31:47 - INFO] - bot - Bot stopped.
[02-May-24 16:31:59 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:31:59 - INFO] - bot - Lets roll
[02-May-24 16:32:37 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:38 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:38 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:38 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:38 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:32:46 - INFO] - bot - Bot stopped.
[02-May-24 16:33:05 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:33:05 - INFO] - bot - Lets roll
[02-May-24 16:35:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:35:36 - INFO] - bot - Bot stopped.
[02-May-24 16:35:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:35:48 - INFO] - bot - Lets roll
[02-May-24 16:42:50 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:42:50 - INFO] - bot - Bot stopped.
[02-May-24 16:44:52 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:44:52 - INFO] - bot - Lets roll
[02-May-24 16:47:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 16:47:00 - INFO] - bot - Bot stopped.
[02-May-24 16:47:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 16:47:25 - INFO] - bot - Lets roll
[02-May-24 17:12:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:12:17 - INFO] - bot - Bot stopped.
[02-May-24 17:12:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:12:27 - INFO] - bot - Lets roll
[02-May-24 17:14:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:14:08 - INFO] - bot - Bot stopped.
[02-May-24 17:14:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:14:16 - INFO] - bot - Lets roll
[02-May-24 17:15:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 17:17:15 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:17:15 - INFO] - bot - Bot stopped.
[02-May-24 17:17:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:17:25 - INFO] - bot - Lets roll
[02-May-24 17:21:58 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:21:58 - INFO] - bot - Bot stopped.
[02-May-24 17:22:07 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:22:07 - INFO] - bot - Lets roll
[02-May-24 17:22:30 - ERROR] - pyrogram.dispatcher - isinstance expected 2 arguments, got 1
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 45, in download_link
    if isinstance(response) is str:
       ^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance expected 2 arguments, got 1
[02-May-24 17:24:09 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:24:09 - INFO] - bot - Bot stopped.
[02-May-24 17:24:23 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:24:23 - INFO] - bot - Lets roll
[02-May-24 17:30:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:30:49 - INFO] - bot - Bot stopped.
[02-May-24 17:31:02 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:31:02 - INFO] - bot - Lets roll
[02-May-24 17:31:04 - ERROR] - pyrogram.dispatcher - Telegram says: [400 MESSAGE_ID_INVALID] - The message id is invalid (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 46, in download_link
    return await message.edit_text(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] - The message id is invalid (caused by "messages.EditMessage")
[02-May-24 17:32:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:32:16 - INFO] - bot - Bot stopped.
[02-May-24 17:32:26 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:32:26 - INFO] - bot - Lets roll
[02-May-24 17:32:29 - ERROR] - pyrogram.dispatcher - Telegram says: [400 MESSAGE_ID_INVALID] - The message id is invalid (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 46, in download_link
    return await message.edit_text(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.MessageIdInvalid: Telegram says: [400 MESSAGE_ID_INVALID] - The message id is invalid (caused by "messages.EditMessage")
[02-May-24 17:33:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:33:02 - INFO] - bot - Bot stopped.
[02-May-24 17:33:11 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:33:11 - INFO] - bot - Lets roll
[02-May-24 17:35:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:35:08 - INFO] - bot - Bot stopped.
[02-May-24 17:35:16 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:35:16 - INFO] - bot - Lets roll
[02-May-24 17:41:15 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:41:15 - INFO] - bot - Bot stopped.
[02-May-24 17:41:24 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:41:24 - INFO] - bot - Lets roll
[02-May-24 17:43:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:43:02 - INFO] - bot - Bot stopped.
[02-May-24 17:43:24 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:43:24 - INFO] - bot - Lets roll
[02-May-24 17:47:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:47:34 - INFO] - bot - Bot stopped.
[02-May-24 17:47:43 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:47:43 - INFO] - bot - Lets roll
[02-May-24 17:47:44 - ERROR] - pyrogram.dispatcher - DownloadManager._find_downloadable_links() missing 1 required positional argument: 'link'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\downloader.py", line 37, in download_link
    link = dm._parse_link(expect_link)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\managers\download\manager.py", line 41, in _parse_link
    "urls": self._find_downloadable_links(link),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DownloadManager._find_downloadable_links() missing 1 required positional argument: 'link'
[02-May-24 17:49:26 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:49:26 - INFO] - bot - Bot stopped.
[02-May-24 17:49:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:49:45 - INFO] - bot - Lets roll
[02-May-24 17:53:27 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:53:27 - INFO] - bot - Bot stopped.
[02-May-24 17:53:35 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:53:35 - INFO] - bot - Lets roll
[02-May-24 17:54:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 17:54:34 - INFO] - bot - Bot stopped.
[02-May-24 17:54:43 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 17:54:43 - INFO] - bot - Lets roll
[02-May-24 18:02:41 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:02:41 - INFO] - bot - Bot stopped.
[02-May-24 18:02:52 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 18:02:52 - INFO] - bot - Lets roll
[02-May-24 18:09:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:09:14 - INFO] - bot - Bot stopped.
[02-May-24 18:09:54 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 18:09:54 - INFO] - bot - Lets roll
[02-May-24 18:10:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 18:10:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 18:10:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 18:10:45 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 18:10:55 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:18 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 18:11:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:21 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 18:11:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:11:24 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[02-May-24 18:11:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[02-May-24 18:13:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 18:13:43 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:13:43 - INFO] - bot - Bot stopped.
[02-May-24 18:15:54 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 18:15:54 - INFO] - bot - Lets roll
[02-May-24 18:20:22 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:20:22 - INFO] - bot - Bot stopped.
[02-May-24 18:21:17 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 18:21:17 - INFO] - bot - Lets roll
[02-May-24 18:30:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:30:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:30:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:30:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:30:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:30:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 18:31:18 - INFO] - bot - Bot stopped.
[02-May-24 18:31:37 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 18:31:37 - INFO] - bot - Lets roll
[02-May-24 18:51:23 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:51:24 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:58:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:58:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:58:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:58:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:58:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 18:59:36 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 18:59:36 - INFO] - bot - Lets roll
[02-May-24 19:00:21 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:00:21 - INFO] - bot - Bot stopped.
[02-May-24 19:00:44 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:00:44 - INFO] - bot - Lets roll
[02-May-24 19:02:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:02:14 - INFO] - bot - Bot stopped.
[02-May-24 19:02:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:02:25 - INFO] - bot - Lets roll
[02-May-24 19:02:54 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:02:54 - INFO] - bot - Bot stopped.
[02-May-24 19:03:24 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:03:24 - INFO] - bot - Lets roll
[02-May-24 19:09:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:09:17 - INFO] - bot - Bot stopped.
[02-May-24 19:10:55 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:10:55 - INFO] - bot - Lets roll
[02-May-24 19:13:19 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:13:19 - INFO] - bot - Bot stopped.
[02-May-24 19:13:29 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:13:29 - INFO] - bot - Lets roll
[02-May-24 19:14:38 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:14:38 - INFO] - bot - Bot stopped.
[02-May-24 19:14:49 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:14:49 - INFO] - bot - Lets roll
[02-May-24 19:16:02 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 19:16:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 19:16:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[02-May-24 19:17:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:17:36 - INFO] - bot - Bot stopped.
[02-May-24 19:17:46 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:17:46 - INFO] - bot - Lets roll
[02-May-24 19:20:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:20:42 - INFO] - bot - Bot stopped.
[02-May-24 19:20:53 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:20:53 - INFO] - bot - Lets roll
[02-May-24 19:23:24 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:23:24 - INFO] - bot - Bot stopped.
[02-May-24 19:23:35 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:23:35 - INFO] - bot - Lets roll
[02-May-24 19:24:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[02-May-24 19:24:42 - INFO] - bot - Bot stopped.
[02-May-24 19:25:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[02-May-24 19:25:20 - INFO] - bot - Lets roll
