[01-May-24 08:38:41 - ERROR] - pyrogram.dispatcher - 'tuple' object has no attribute 'telegram_id'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\start.py", line 191, in get_users
    users = await full_userbase()
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\database\database.py", line 23, in full_userbase
    telegram_ids.append(doc.telegram_id)
                        ^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'telegram_id'
[01-May-24 08:40:18 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 08:40:18 - INFO] - bot - Bot stopped.
[01-May-24 08:40:25 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 08:40:25 - INFO] - bot - Lets roll
[01-May-24 08:45:06 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 08:45:06 - INFO] - bot - Bot stopped.
[01-May-24 08:45:32 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 08:45:32 - INFO] - bot - Lets roll
[01-May-24 08:50:18 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 08:50:18 - INFO] - bot - Bot stopped.
[01-May-24 08:50:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 08:50:33 - INFO] - bot - Lets roll
[01-May-24 08:50:47 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 17, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 08:50:57 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 17, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 08:51:22 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 17, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 08:53:21 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 08:53:21 - INFO] - bot - Bot stopped.
[01-May-24 08:53:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 08:53:33 - INFO] - bot - Lets roll
[01-May-24 08:53:36 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 19, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 08:53:49 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 08:53:49 - INFO] - bot - Bot stopped.
[01-May-24 08:54:01 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 08:54:01 - INFO] - bot - Lets roll
[01-May-24 08:54:15 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 19, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 08:55:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 08:55:10 - INFO] - bot - Bot stopped.
[01-May-24 08:55:21 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 08:55:21 - INFO] - bot - Lets roll
[01-May-24 09:00:01 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:00:01 - INFO] - bot - Bot stopped.
[01-May-24 09:00:14 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:00:14 - INFO] - bot - Lets roll
[01-May-24 09:02:39 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:02:39 - INFO] - bot - Bot stopped.
[01-May-24 09:03:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:03:28 - INFO] - bot - Lets roll
[01-May-24 09:07:46 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:07:46 - INFO] - bot - Bot stopped.
[01-May-24 09:07:59 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:07:59 - INFO] - bot - Lets roll
[01-May-24 09:12:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:12:14 - INFO] - bot - Bot stopped.
[01-May-24 09:12:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:12:27 - INFO] - bot - Lets roll
[01-May-24 09:16:29 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:16:29 - INFO] - bot - Bot stopped.
[01-May-24 09:16:44 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:16:44 - INFO] - bot - Lets roll
[01-May-24 09:18:46 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:18:46 - INFO] - bot - Bot stopped.
[01-May-24 09:19:02 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:19:02 - INFO] - bot - Lets roll
[01-May-24 09:19:43 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:19:43 - INFO] - bot - Bot stopped.
[01-May-24 09:19:55 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:19:55 - INFO] - bot - Lets roll
[01-May-24 09:33:03 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:33:03 - INFO] - bot - Bot stopped.
[01-May-24 09:33:21 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:33:21 - INFO] - bot - Lets roll
[01-May-24 09:45:25 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 09:45:25 - INFO] - bot - Bot stopped.
[01-May-24 09:45:50 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 09:45:50 - INFO] - bot - Lets roll
[01-May-24 10:01:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 10:01:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:16 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:19 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:22 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:25 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:25 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:28 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:31 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:34 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:37 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:40 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:43 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:46 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:46 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:47 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:48 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:49 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:49 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:50 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:51 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:52 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:53 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:54 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:56 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:56 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:57 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:58 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:01:59 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:01:59 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:00 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:01 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:02 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:02 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:03 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:04 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:05 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:05 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:06 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:07 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:08 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:08 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:09 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:10 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:11 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:11 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:12 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:14 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:17 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:20 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:23 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:25 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:26 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:29 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:32 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:35 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:38 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:41 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:44 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:46 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:47 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:47 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:48 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:49 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:50 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:50 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:51 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:53 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:53 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:54 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:55 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:56 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:56 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:57 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:58 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:02:59 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:02:59 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:00 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:01 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:02 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:02 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:03 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:04 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:05 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:05 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:06 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:07 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:08 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:08 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:09 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:10 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:11 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:11 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:12 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:14 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:17 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:21 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:24 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:25 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:27 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:30 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:33 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:36 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:39 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:42 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:45 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:46 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:47 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:48 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:48 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:49 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:50 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:51 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:51 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:53 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:54 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:54 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:55 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:56 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:03:57 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 10:03:57 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 10:33:58 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 10:33:58 - INFO] - bot - Bot stopped.
[01-May-24 10:34:14 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 10:34:14 - INFO] - bot - Lets roll
[01-May-24 11:10:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 11:17:43 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:17:43 - INFO] - bot - Bot stopped.
[01-May-24 11:17:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:17:51 - INFO] - bot - Lets roll
[01-May-24 11:18:03 - ERROR] - pyrogram.dispatcher - search() missing 1 required positional argument: 'range'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 27, in search_command
    results = search(query)
              ^^^^^^^^^^^^^
TypeError: search() missing 1 required positional argument: 'range'
[01-May-24 11:19:50 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:19:50 - INFO] - bot - Bot stopped.
[01-May-24 11:19:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:19:56 - INFO] - bot - Lets roll
[01-May-24 11:20:10 - ERROR] - pyrogram.dispatcher - cannot access local variable 'matched_results' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 27, in search_command
    results = search(query)
              ^^^^^^^^^^^^^
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 12, in search
    matched_results,unmatched_results, other_links = scraper.filter_links(matched_results)
                                                                          ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'matched_results' where it is not associated with a value
[01-May-24 11:21:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 11:21:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 11:22:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 11:22:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 11:22:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 11:22:44 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 11:22:56 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:22:56 - INFO] - bot - Bot stopped.
[01-May-24 11:23:04 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:23:04 - INFO] - bot - Lets roll
[01-May-24 11:25:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:25:00 - INFO] - bot - Bot stopped.
[01-May-24 11:25:07 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:25:07 - INFO] - bot - Lets roll
[01-May-24 11:33:22 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:33:22 - INFO] - bot - Bot stopped.
[01-May-24 11:33:29 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:33:29 - INFO] - bot - Lets roll
[01-May-24 11:33:57 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:33:57 - INFO] - bot - Bot stopped.
[01-May-24 11:34:04 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:34:04 - INFO] - bot - Lets roll
[01-May-24 11:36:05 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:36:05 - INFO] - bot - Bot stopped.
[01-May-24 11:36:12 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:36:12 - INFO] - bot - Lets roll
[01-May-24 11:36:27 - ERROR] - pyrogram.dispatcher - 'list' object has no attribute 'join'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 28, in search_command
    matched_year.join(unmatched_year)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'join'
[01-May-24 11:37:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:37:10 - INFO] - bot - Bot stopped.
[01-May-24 11:37:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:37:19 - INFO] - bot - Lets roll
[01-May-24 11:53:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:53:42 - INFO] - bot - Bot stopped.
[01-May-24 11:53:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:53:51 - INFO] - bot - Lets roll
[01-May-24 11:58:20 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:58:20 - INFO] - bot - Bot stopped.
[01-May-24 11:58:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:58:28 - INFO] - bot - Lets roll
[01-May-24 11:59:33 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 11:59:33 - INFO] - bot - Bot stopped.
[01-May-24 11:59:40 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 11:59:40 - INFO] - bot - Lets roll
[01-May-24 11:59:43 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 18, in search_command
    mg = await message.reply_text(f"<code>Searching for <u>{query}...</u><code>")
                                                            ^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:00:24 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 18, in search_command
    mg = await message.reply_text(f"<code>Searching for <u>{query}...</u><code>")
                                                            ^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:02:32 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:02:32 - INFO] - bot - Bot stopped.
[01-May-24 12:02:40 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:02:40 - INFO] - bot - Lets roll
[01-May-24 12:04:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:04:02 - INFO] - bot - Bot stopped.
[01-May-24 12:04:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:04:08 - INFO] - bot - Lets roll
[01-May-24 12:05:42 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:05:42 - INFO] - bot - Bot stopped.
[01-May-24 12:05:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:05:51 - INFO] - bot - Lets roll
[01-May-24 12:06:05 - ERROR] - pyrogram.dispatcher - Invalid parse mode "html"
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 40, in search_command
    await msg.edit_text(
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\edit_message_text.py", line 88, in edit_message_text
    **await utils.parse_text_entities(self, text, parse_mode, entities)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\utils.py", line 354, in parse_text_entities
    text, entities = (await client.parser.parse(text, parse_mode)).values()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\parser\parser.py", line 54, in parse
    raise ValueError(f'Invalid parse mode "{mode}"')
ValueError: Invalid parse mode "html"
[01-May-24 12:06:47 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:06:47 - INFO] - bot - Bot stopped.
[01-May-24 12:06:53 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:06:53 - INFO] - bot - Lets roll
[01-May-24 12:07:40 - ERROR] - pyrogram.dispatcher - Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 40, in search_command
    await msg.edit_text(
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonDataInvalid: Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.EditMessage")
[01-May-24 12:08:33 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:08:33 - INFO] - bot - Bot stopped.
[01-May-24 12:08:39 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:08:39 - INFO] - bot - Lets roll
[01-May-24 12:08:52 - ERROR] - pyrogram.dispatcher - Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.EditMessage")
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 40, in search_command
    await msg.edit_text(
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\types\messages_and_media\message.py", line 2803, in edit_text
    return await self._client.edit_message_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\messages\edit_message_text.py", line 82, in edit_message_text
    r = await self.invoke(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\methods\advanced\invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\session\session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\errors\rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ButtonDataInvalid: Telegram says: [400 BUTTON_DATA_INVALID] - The button callback data is invalid or too large (caused by "messages.EditMessage")
[01-May-24 12:09:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:09:11 - INFO] - bot - Bot stopped.
[01-May-24 12:09:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:09:18 - INFO] - bot - Lets roll
[01-May-24 12:23:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:23:36 - INFO] - bot - Bot stopped.
[01-May-24 12:23:44 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:23:44 - INFO] - bot - Lets roll
[01-May-24 12:31:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:31:17 - INFO] - bot - Bot stopped.
[01-May-24 12:31:26 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:31:26 - INFO] - bot - Lets roll
[01-May-24 12:38:35 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:38:35 - INFO] - bot - Bot stopped.
[01-May-24 12:38:41 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:38:41 - INFO] - bot - Lets roll
[01-May-24 12:48:38 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 21, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 12:48:46 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:48:46 - INFO] - bot - Bot stopped.
[01-May-24 12:48:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:48:56 - INFO] - bot - Lets roll
[01-May-24 12:49:47 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 21, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 12:50:31 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:50:31 - INFO] - bot - Bot stopped.
[01-May-24 12:50:37 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:50:37 - INFO] - bot - Lets roll
[01-May-24 12:50:41 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 21, in search_command
    query = message.text.split(" ", 1)[1].strip()
            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 12:51:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:51:04 - INFO] - bot - Bot stopped.
[01-May-24 12:51:11 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:51:11 - INFO] - bot - Lets roll
[01-May-24 12:51:15 - ERROR] - pyrogram.dispatcher - list index out of range
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 18, in search_command
    if not message.text.split(" ", 1)[1]:
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[01-May-24 12:52:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:52:11 - INFO] - bot - Bot stopped.
[01-May-24 12:52:17 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:52:17 - INFO] - bot - Lets roll
[01-May-24 12:54:46 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:54:46 - INFO] - bot - Bot stopped.
[01-May-24 12:55:12 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 24, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                                             ^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:55:13 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:55:13 - INFO] - bot - Lets roll
[01-May-24 12:55:44 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:55:44 - INFO] - bot - Bot stopped.
[01-May-24 12:55:52 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:55:52 - INFO] - bot - Lets roll
[01-May-24 12:56:17 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 24, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                                             ^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:56:45 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 24, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:57:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:05 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 24, in search_command
    matched_year, unmatched_year, others = search(query)
                                   ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:57:07 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:07 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:07 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:10 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:11 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:14 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:17 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:26 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 24, in search_command
    matched_year, unmatched_year, others = search(query)
                                   ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:57:27 - INFO] - bot - Bot stopped.
[01-May-24 12:57:33 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:57:33 - INFO] - bot - Lets roll
[01-May-24 12:57:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 12:57:34 - INFO] - bot - Bot stopped.
[01-May-24 12:57:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 12:57:45 - INFO] - bot - Lets roll
[01-May-24 12:57:45 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 23, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                                             ^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:57:49 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 23, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:57:50 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 23, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:57:52 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 23, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 12:57:56 - ERROR] - pyrogram.dispatcher - cannot access local variable 'query' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 23, in search_command
    msg = await message.reply_text(f"<code>Searching for <u>{query}</u><code>")
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'query' where it is not associated with a value
[01-May-24 13:01:57 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:01:57 - INFO] - bot - Bot stopped.
[01-May-24 13:02:05 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:02:05 - INFO] - bot - Lets roll
[01-May-24 13:02:20 - ERROR] - pyrogram.dispatcher - searching.insert_searching() missing 1 required positional argument: 'searched_for'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 45, in search_command
    searching.insert_searching(msg.chat.id, query)
TypeError: searching.insert_searching() missing 1 required positional argument: 'searched_for'
[01-May-24 13:03:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:03:00 - INFO] - bot - Bot stopped.
[01-May-24 13:03:07 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:03:07 - INFO] - bot - Lets roll
[01-May-24 13:03:18 - ERROR] - pyrogram.dispatcher - searching.insert_searching() missing 1 required positional argument: 'searched_for'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 45, in search_command
    searching.insert_searching(msg.chat.id, query)
TypeError: searching.insert_searching() missing 1 required positional argument: 'searched_for'
[01-May-24 13:04:01 - ERROR] - pyrogram.dispatcher - searching.insert_searching() missing 1 required positional argument: 'searched_for'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 45, in search_command
    searching.insert_searching(msg.chat.id, query)
TypeError: searching.insert_searching() missing 1 required positional argument: 'searched_for'
[01-May-24 13:05:01 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:05:01 - INFO] - bot - Bot stopped.
[01-May-24 13:05:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:05:08 - INFO] - bot - Lets roll
[01-May-24 13:05:23 - ERROR] - pyrogram.dispatcher - searching.insert_searching() missing 1 required positional argument: 'searched_for'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\search_items.py", line 45, in search_command
    searching.insert_searching(msg.chat.id, query)
TypeError: searching.insert_searching() missing 1 required positional argument: 'searched_for'
[01-May-24 13:05:58 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:05:58 - INFO] - bot - Bot stopped.
[01-May-24 13:06:07 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:06:07 - INFO] - bot - Lets roll
[01-May-24 13:10:41 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:10:41 - INFO] - bot - Bot stopped.
[01-May-24 13:10:46 - ERROR] - pyrogram.dispatcher - 'Bot' object has no attribute 'uptime'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\useless.py", line 14, in stats
    delta = now - bot.uptime
                  ^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'uptime'
[01-May-24 13:10:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:10:48 - INFO] - bot - Lets roll
[01-May-24 13:13:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:13:02 - INFO] - bot - Bot stopped.
[01-May-24 13:13:09 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:13:09 - INFO] - bot - Lets roll
[01-May-24 13:13:33 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:13:33 - INFO] - bot - Bot stopped.
[01-May-24 13:13:41 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:13:41 - INFO] - bot - Lets roll
[01-May-24 13:15:16 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:15:16 - INFO] - bot - Bot stopped.
[01-May-24 13:15:22 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:15:22 - INFO] - bot - Lets roll
[01-May-24 13:18:21 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:18:21 - INFO] - bot - Bot stopped.
[01-May-24 13:18:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:18:28 - INFO] - bot - Lets roll
[01-May-24 13:19:13 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:19:13 - INFO] - bot - Bot stopped.
[01-May-24 13:19:20 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:19:20 - INFO] - bot - Lets roll
[01-May-24 13:21:53 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:21:53 - INFO] - bot - Bot stopped.
[01-May-24 13:22:00 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:22:00 - INFO] - bot - Lets roll
[01-May-24 13:22:20 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:22:20 - INFO] - bot - Bot stopped.
[01-May-24 13:22:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:22:27 - INFO] - bot - Lets roll
[01-May-24 13:22:47 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:22:47 - INFO] - bot - Bot stopped.
[01-May-24 13:22:54 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:22:54 - INFO] - bot - Lets roll
[01-May-24 13:24:48 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:24:48 - INFO] - bot - Bot stopped.
[01-May-24 13:24:56 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:24:56 - INFO] - bot - Lets roll
[01-May-24 13:26:04 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: Connection timed out
[01-May-24 13:26:05 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:06 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:07 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:07 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:08 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:09 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:10 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:10 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:11 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:12 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:13 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:16 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:19 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:22 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:25 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:25 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:28 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:31 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:34 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:37 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:40 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:43 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:45 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:46 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:46 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:47 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:48 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:49 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:49 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:50 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:51 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:52 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:53 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:54 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:56 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:56 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:57 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:58 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:26:59 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:26:59 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:00 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:01 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:02 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:02 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:03 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:04 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:05 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:05 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:06 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:07 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:08 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:08 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:09 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:10 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:11 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:11 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:12 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:13 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:14 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:14 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:15 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:16 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:17 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:17 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:18 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:19 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:20 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:20 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:21 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:22 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:23 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:23 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:24 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:25 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:26 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:26 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:27 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:27:29 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[01-May-24 13:27:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
[01-May-24 13:30:31 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:30:31 - INFO] - bot - Bot stopped.
[01-May-24 13:30:43 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:30:43 - INFO] - bot - Lets roll
[01-May-24 13:31:53 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:31:53 - INFO] - bot - Bot stopped.
[01-May-24 13:32:00 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:32:00 - INFO] - bot - Lets roll
[01-May-24 13:32:22 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:32:22 - INFO] - bot - Bot stopped.
[01-May-24 13:32:29 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:32:29 - INFO] - bot - Lets roll
[01-May-24 13:34:19 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:34:19 - INFO] - bot - Bot stopped.
[01-May-24 13:34:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:34:27 - INFO] - bot - Lets roll
[01-May-24 13:34:29 - ERROR] - pyrogram.dispatcher - list.count() takes exactly one argument (0 given)
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\useless.py", line 18, in stats
    print(queries.count())
          ^^^^^^^^^^^^^^^
TypeError: list.count() takes exactly one argument (0 given)
[01-May-24 13:35:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:35:04 - INFO] - bot - Bot stopped.
[01-May-24 13:35:12 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:35:12 - INFO] - bot - Lets roll
[01-May-24 13:35:41 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:35:41 - INFO] - bot - Bot stopped.
[01-May-24 13:35:47 - ERROR] - pyrogram.dispatcher - 'Bot' object has no attribute 'uptime'
Traceback (most recent call last):
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "C:\Users\manfr\AppData\Roaming\Python\Python311\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "C:\WorkSpace\Apps\Bots\File-Sharing-Bot\plugins\useless.py", line 14, in stats
    delta = now - bot.uptime
                  ^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'uptime'
[01-May-24 13:35:48 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:35:48 - INFO] - bot - Lets roll
[01-May-24 13:37:01 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:37:01 - INFO] - bot - Bot stopped.
[01-May-24 13:37:08 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:37:08 - INFO] - bot - Lets roll
[01-May-24 13:37:35 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:37:35 - INFO] - bot - Bot stopped.
[01-May-24 13:37:43 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:37:43 - INFO] - bot - Lets roll
[01-May-24 13:38:59 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:38:59 - INFO] - bot - Bot stopped.
[01-May-24 13:39:11 - INFO] - bot - Bot Running..!

Created by 
https://t.me/stilloid
[01-May-24 13:39:11 - INFO] - bot - Lets roll
[01-May-24 13:46:36 - INFO] - root - Stop signal received (SIGINT). Exiting...
[01-May-24 13:46:36 - INFO] - bot - Bot stopped.
